language: java
jdk: openjdk17
version: ~> 1.0
os: linux
dist: jammy
services: docker
addons:
  hosts:
    - mariadb.example.com
    - mariadb1.example.com
    - mariadb2.example.com
    - mariadb3.example.com


before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install openjdk11 maven
        export PATH=$(cmd.exe //c "refreshenv > nul & C:\Progra~1\Git\bin\bash -c 'echo \$PATH' ")
        ;;
    esac

install:
  - git clone https://github.com/mariadb-corporation/connector-test-machine.git
  - |-
    if [ -z "$server_branch" ] ; then
      case $TRAVIS_OS_NAME in
        windows)
          connector-test-machine/launch.bat -t "$srv" -v "$v" -d "$DB"
          # Since refreshenv doesn't seem to work, we set this manually
          export WIX="/c/Program Files (x86)/WiX Toolset v3.11"
          ;;
        linux)
          source connector-test-machine/launch.sh -t "$srv" -v "$v" -d "$DB" -l "$local" -c "$CLEAR_TEXT" -p "$packet"
          ;;
      esac
    fi

env:
  global: local=0 RUN_LONG_TEST=true PROFILE=default DB=testj CLEAR_TEXT=0

jobs:
  include:
    - env: srv=mariadb-es-test v=11.4
      jdk: openjdk17
      name: "ES 11.4 - openjdk 8"

script:
  - echo $PROFILE
  - mvn clean -Dmaven.test.skip -P $PROFILE
  - |-
    if [ "java8" == "$PROFILE" ]; then
      rm -R .mvn
          java -version
      mvn -version
    fi
  - if [ -n "$BENCH" ] ; then mvn package -P bench -Dmaven.test.skip -Dmaven.javadoc.skip=true ; fi
  - if [ -n "$BENCH" ] ; then java -Duser.country=US -Duser.language=en -DTEST_PORT=$TEST_DB_PORT -DTEST_HOST=$TEST_DB_HOST -DTEST_USERNAME=$TEST_DB_USER -DTEST_PASSWORD=$TEST_DB_PASSWORD -jar target/benchmarks.jar; fi
  - if [ -z "$BENCH" ] ; then MAVEN_SKIP_RC=true MAVEN_OPTS="-Xmx2g" mvn clean test -P ${PROFILE} -DjobId=${TRAVIS_JOB_ID}; fi

after_script:
  - bash <(curl -s https://codecov.io/bash)
