# ************************************************************************************
#   Copyright (c) 2021-2025 SingleStore, Inc.
#
#   This library is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Library General Public
#   License as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#
#   This library is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Library General Public License for more details.
#
#   You should have received a copy of the GNU Library General Public
#   License along with this library; if not see <http://www.gnu.org/licenses>
#   or write to the Free Software Foundation, Inc.,
#   51 Franklin St., Fifth Floor, Boston, MA 02110, USA
# *************************************************************************************/
---
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch-s2-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - name: Get supported versions of SingleStore
        id: get_versions
        uses: singlestore-labs/singlestore-supported-versions@main
        with:
          include_rc: true

  test:
    needs: fetch-s2-versions
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        singlestore_version: ${{ fromJson(needs.fetch-s2-versions.outputs.versions) }}
    permissions:
      checks: write
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: Free up disk space
        run: ./scripts/ci/free-disk-space.sh
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install MariaDB client
        run: sudo apt-get update && sudo apt-get install -y mariadb-client

      - name: Setup test cluster
        run: ./scripts/ensure-test-singlestore-cluster-password.sh
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: ${{ secrets.SINGLESTORE_PASSWORD }}
          SINGLESTORE_VERSION: ${{ matrix.singlestore_version }}

      - name: Run tests with Maven
        run: mvn -B test

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4.0.0
